### ISSUE TITLE
nuspec is using direct .dll reference instead of package.

### ISSUE THREAD

**Issue by jzeferino** [cake-contrib/Cake.ResxConverter#1]
The Cake.ResxConverter .nuspec has references to the .dll dependencies. Could make sense to reference nuget packages instead.

**Comment by luisgoncalves** [comment]
I think Cake addins must include all the needed assemblies in the package. Cake won't go through the package dependencies to add other assemblies.

**Comment by jzeferino** [comment]
But its a Cake thing? Guess I've seen .net library​s referencing other dependcies via package reference.

**Comment by luisgoncalves** [comment]
Yeah, a detail on Cake usage of packages. But I'm not 100% sure. Need to
check.

**Comment by luisgoncalves** [comment]
I've double checked this with the Cake team. All the dependencies should be contained in the addin package.
