### ISSUE TITLE
Add to cake contrib

### ISSUE THREAD

**Issue by jzeferino** [cake-contrib/Cake.ResxConverter#2]

**Comment by luisgoncalves** [comment]
https://github.com/cake-contrib/Home

**Comment by luisgoncalves** [comment]
I spoke to `gep13` and the first step is to pass ownership of the repo to him, as explained [here](https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation). He'll then add it to the organization.

I don't have the required permissions, so you have to do this.

**Comment by jzeferino** [comment]
Did it. Lets wait.

**Comment by luisgoncalves** [comment]
The repo was moved. We still need to add the `cake-contrib` user on NuGet.org and wait for the configuration of the AppVeyor project.

**Comment by jzeferino** [comment]
cake-contrib added as nuget owner.

**Comment by gep13** [comment]
@jzeferino nice one, thank you very much!

**Comment by gep13** [comment]
@jzeferino @luisgoncalves the AppVeyor Build has now been configured for this repository.  If you sign into AppVeyor using your GitHub accounts, you should be able to see it.  Thanks!

**Comment by jzeferino** [comment]
@gep13 My Appveyor account was already logged with my github account. I don't find the project there. 
Note: I also deleted my old appveyor project configuration for Cake.ResxConverter.

**Comment by gep13** [comment]
@jzeferino you may need to log out and log back in again in order for it to show up.

**Comment by jzeferino** [comment]
I've logged out and looged in as cake-contrib and I can see it. Will update the project readme for the new appveyor project keys. Thanks.

**Comment by gep13** [comment]
Perfect!

**Comment by jzeferino** [comment]
@gep13  Can you give the badge code for the README? I don't have permissions.

**Comment by gep13** [comment]
@jzeferino log out and log back in again, see if you can see it now.

**Comment by jzeferino** [comment]
Its good now.

**Comment by jzeferino** [comment]
@gep13 Its good now.
@gep13 Whats do I need to do to make the addin and documentation appear in the cake website?

**Comment by gep13** [comment]
@jzeferino have a look at the issue I raised on another add in repo here:

https://github.com/kolletzki/Cake.UncUtils/issues/2

For more information.

**Comment by jzeferino** [comment]
@gep13  I've already made the [PR](https://github.com/cake-build/website/pull/340) for the .yml.

**Comment by gep13** [comment]
@jzeferino @luisgoncalves I think we are in a position to close this out, right?

**Comment by luisgoncalves** [comment]
Indeed.
